from django.urls import path
from bill_coll import views
app_name = 'bill_coll'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('Dashboard', views.Dashboard, name = 'Dashboard'),
    path('admin_Dashboard', views.admin_Dashboard, name = 'admin_Dashboard'),
    path('consumer_Dashboard', views.consumer_Dashboard, name = 'consumer_Dashboard'),
    path('Users', views.Users, name = 'Users'),
    path('Collections', views.Collections, name = 'Collections'),
    path('Packages', views.Packages, name = 'Packages'),
    path('Home', views.Home, name = 'Home'),
    path('signup', views.signup, name = 'signup'),
    path('signin', views.signin, name = 'signin'),
    path('logout', views.logout, name = 'logout'),
    path('addpackage', views.addpackage, name = 'addpackage'),
    path('viewpackage/<int:package_id>/', views.viewpackage, name = 'viewpackage'),
    path('editpackage/<int:package_id>/', views.editpackage, name = 'editpackage'),
    path('deletepackage/<int:package_id>/', views.deletepackage, name = 'deletepackage'),
    path('addcity', views.addcity, name = 'addcity'),
    path('viewcity/<int:city_id>/', views.viewcity, name = 'viewcity'),
    path('editcity/<int:city_id>/', views.editcity, name = 'editcity'),
    path('deletecity/<int:city_id>/', views.deletecity, name = 'deletecity'),
    path('addarea', views.addarea, name = 'addarea'),
    path('viewarea/<int:area_id>/', views.viewarea, name = 'viewarea'),
    path('editarea/<int:area_id>/', views.editarea, name = 'editarea'),
    path('deletearea/<int:area_id>/', views.deletearea, name = 'deletearea'),
    path('addcollection', views.addcollection, name = 'addcollection'),
    path('viewcollection/<int:collection_id>/', views.viewcollection, name = 'viewcollection'),
    path('editcollection/<int:collection_id>/', views.editcollection, name = 'editcollection'),
    path('deletecollection/<int:collection_id>/', views.deletecollection, name = 'deletecollection'),
    path('user/<int:pk>/', views.update_profile, name='update_profile'),
    path('ajax/load-areas/', views.load_areas, name='ajax_load_areas'),
]