# Generated by Django 4.1.4 on 2023-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_coll', '0002_remove_collection_date_alter_collection_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
