# Generated by Django 4.1.4 on 2023-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_coll', '0003_profile_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
