# Generated by Django 4.1.4 on 2023-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_coll', '0008_alter_collection_billmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paidThruMonth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
